snippet_path: "<Your vscode or cursor path here>/User/snippets/python.json"
library_path: "<Your library path here>"
mark_path: "<library_mark_template.yaml path here>"

# is_overwrite >= 1 : スニペット更新時は上書き、is_overwrite <= 0 : スニペット更新時は新規作成
is_overwrite: 1

# "<something string>": 指定文字のフォルダを作成し更新前のスニペットをバックアップとして保存、"": バックアップ未実施
backup_path: ".backup"

# python sample
extensions: [".py"]
excludes: ["__pycache__"]
